version: '{branch}-{build}'
environment:
  PY_PYTHON: 3.7-32
install:
- cmd: >-
    set PATH=C:\Python37\Scripts;%PATH%

    python -m pip install -U pip

    pip install wheel
    
    pip install scons

    pip install markdown
build_script:
- cmd: scons
artifacts:
- path: '*.nvda-addon'
  name: addon
  type: WebDeployPackage
before_deploy:
- ps: $env:REPO_NAME =  $env:APPVEYOR_REPO_NAME.Substring($env:APPVEYOR_REPO_NAME.IndexOf('/') + 1)
deploy:
  provider: FTP
  protocol: ftp
  host:
    secure: bDtLCP8Qj8t2OTKKDEB9LEH4bSHgjmE94Qd3kmsElrg=
  username:
    secure: UdaIlHk5Q87ZnydXu7PpBw==
  password:
    secure: jdngQAtlVxo7GQokRXAhAQ==
  folder: /nvda-addons
  beta: true
  debug: true
  artifact: addon
  on:
    appveyor_repo_tag: true